### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [JanCaha/qgis_los_tools#1]
The functionality described in the About seems already present in core QGIS.
Please clarify what the plugin is actually adding.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by JanCaha** [comment]
I don't think that there are tools for the creation of lines-of-sight (point to point visibility) and their analyses (e.g. horizon and horizon lines extraction) in QGIS. There are tools in GRASS available, but those are functionally different from the plugin.

The description of the plugin can and definitely will be improved with upcoming versions. 

The second part of the question brings up a kind of philosophical question. Is it really a bad thing to have a duplicated functionality? It is unlikely that the details of the algorithms are exactly the same, two programmers will not solve the given issue with identical algorithms. Even minor differences might be interesting for certain users or specific situations. So I am not sure if this is a reasonable approach (maybe even mindset) especially for FOSS and in a situation when plugins, which don't have to be installed and their management is purely up to the user, are discussed.

**Comment by pcav** [comment]
May I ask you to improve the About, adding a bit more context?
Re: duplication, it's a complex matter, better discuss about it in qgis-dev ML.
Thanks.

**Comment by ghtmtt** [comment]
@JanCaha I often use the plugin Visibility Analysis (http://www.zoran-cuckovic.from.hr/QGIS-visibility-analysis/help_qgis3.html). Are there additional functions in your plugin?

**Comment by pcav** [comment]
It would be preferable to merge the two unless there are very good reasons not to.
I'm available for facilitating this process.

**Comment by JanCaha** [comment]
Visibility Analysis plugin works on point (observer) to area principle and the outcomes are mostly raster data. LoS tools works on point to point principle and it deals with more detailed analyses of individual lines-of-sight. You can also use it to extract horizon points as well as horizon lines. 

I updated the [site](https://jancaha.github.io/qgis_los_tools/) a little bit and will ad some practical examples later.

**Comment by pcav** [comment]
Thanks. It would be great to integrate the two.
