### ISSUE TITLE
Please explain website

### ISSUE THREAD

**Issue by pcav** [JanCaha/qgis_los_tools#2]
why has this been included in source code?
Cheers.

**Comment by JanCaha** [comment]
It is there purely to have everything in one repository, the plugin and the website, which is pretty much help for the plugin. It automatically builds from the directory to github pages and is available at: https://jancaha.github.io/qgis_los_tools/ (there is still a lot of work to do on the website).  

It is not included in the release zip file uploaded to QGIS Plugin website.

**Comment by pcav** [comment]
It makes sense to me, thanks.
May I ask you to improve the About, adding a bit more context?
Thanks.
